//! Item designs. The region below is generated from game/items/set1/*.toml by
//! tools/compile_items.py; edit the TOML, not this block.
#![allow(unused_imports)]
use tapstone_rules::{Faction, Keyword};

use crate::{Item, ItemDesign, Slot};

// Unused only while the generated table is empty (Task 1, before compile_items.py first runs).
#[allow(dead_code)]
const fn item(
    id: u16,
    name: &'static str,
    faction: Faction,
    slot: Slot,
    effect: Item,
    min_level: u8,
    loot: bool,
) -> ItemDesign {
    ItemDesign {
        id,
        name,
        faction,
        slot,
        effect,
        min_level,
        loot,
    }
}

// BEGIN GENERATED ITEMS1
// Generated by tools/compile_items.py from game/items/set1/*.toml — do not edit by hand.
#[rustfmt::skip]
pub static ITEMS: &[ItemDesign] = &[
    item(0, "Ember Sabre", Faction::Ember, Slot::Weapon, Item::Keyword(Keyword::Haste), 1, true),
    item(1, "Tide Trident", Faction::Tide, Slot::Weapon, Item::Look, 1, true),
    item(2, "Hearthguard Plate", Faction::Neutral, Slot::Armour, Item::Keyword(Keyword::Taunt), 3, true),
    item(3, "Driftcloak", Faction::Tide, Slot::Armour, Item::Look, 1, true),
    item(4, "Ash Locket", Faction::Ember, Slot::Trinket, Item::Look, 7, true),
    item(5, "Pearl Charm", Faction::Tide, Slot::Trinket, Item::Look, 7, true),
];
// END GENERATED ITEMS1
