#!/usr/bin/env python3
"""Compile game/items/<set>/*.toml into the generated region of tapstone-progression's items.rs.

Python >= 3.11 (tomllib). Mirrors tools/compile_cards.py: validates the closed vocabularies
(spec 2026-09-23-arena-service-design.md §8.3, decisions 0031 and 0034) and rewrites the text
between `// BEGIN GENERATED ITEMS<N>` and `// END GENERATED ITEMS<N>`. Byte-exact idempotent.
Exit 0 ok · 1 plumbing error · 2 validation error · 3 (--check) the committed file is stale.
"""
import sys

if sys.version_info < (3, 11):
    sys.exit("compile_items.py needs Python 3.11+ (tomllib)")

import argparse
import re
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

FACTIONS = {"ember": "Faction::Ember", "tide": "Faction::Tide", "neutral": "Faction::Neutral"}
SLOTS = {"weapon": "Slot::Weapon", "armour": "Slot::Armour", "trinket": "Slot::Trinket"}
# 0034: gear grants Haste or Taunt, or is a look. Ranged, Shield 1 and Rush never go on a commander.
EFFECTS = {
    "haste": "Item::Keyword(Keyword::Haste)",
    "taunt": "Item::Keyword(Keyword::Taunt)",
    "look": "Item::Look",
}
THIRD_SLOT_AT = 7
KNOWN_KEYS = {"id", "name", "faction", "slot", "effect", "min_level", "loot", "version", "sprite", "flavor"}
ID_RE = re.compile(r"^([a-z]+[0-9]+)-([0-9]{3})$")
SET_RE = re.compile(r"^set([0-9]+)$")


class Invalid(Exception):
    pass


def parse_item(path, id_prefix):
    d = tomllib.loads(path.read_text(encoding="utf-8"))
    unknown = set(d) - KNOWN_KEYS
    if unknown:
        raise Invalid(f"unknown keys: {', '.join(sorted(unknown))}")
    iid = d.get("id")
    m = ID_RE.match(iid) if isinstance(iid, str) else None
    if not m or m[1] != id_prefix:
        raise Invalid(f"`id` must look like {id_prefix}-NNN, got {iid!r}")
    if path.stem != iid:
        raise Invalid(f"file name {path.name!r} does not match id {iid!r}")
    name = d.get("name")
    if not isinstance(name, str) or not name.strip() or '"' in name or "\\" in name:
        raise Invalid("`name` must be a non-empty string without quotes or backslashes")
    if d.get("faction") not in FACTIONS:
        raise Invalid(f"`faction` must be one of {sorted(FACTIONS)}, got {d.get('faction')!r}")
    if d.get("slot") not in SLOTS:
        raise Invalid(f"`slot` must be one of {sorted(SLOTS)}, got {d.get('slot')!r}")
    if d.get("effect") not in EFFECTS:
        raise Invalid(
            f"`effect` must be one of {sorted(EFFECTS)} (0034), got {d.get('effect')!r}"
        )
    lvl = d.get("min_level")
    if isinstance(lvl, bool) or not isinstance(lvl, int) or not 1 <= lvl <= 10:
        raise Invalid(f"`min_level` must be an integer 1..=10, got {lvl!r}")
    if d["slot"] == "trinket" and lvl < THIRD_SLOT_AT:
        raise Invalid(f"a trinket cannot drop before level {THIRD_SLOT_AT}, when its slot opens")
    loot = d.get("loot")
    if not isinstance(loot, bool):
        raise Invalid(f"`loot` must be true or false, got {loot!r}")
    version = d.get("version")
    if isinstance(version, bool) or not isinstance(version, int) or version < 1:
        raise Invalid(f"`version` must be an integer >= 1, got {version!r}")
    index = int(m[2])
    row = (
        f'item({index}, "{name}", {FACTIONS[d["faction"]]}, {SLOTS[d["slot"]]}, '
        f'{EFFECTS[d["effect"]]}, {lvl}, {"true" if loot else "false"})'
    )
    return index, row


def compile_items(set_name, out_path, check=False):
    sm = SET_RE.match(set_name)
    if not sm:
        raise Invalid(f"set name must look like setN, got {set_name!r}")
    id_prefix = f"it{sm[1]}"
    region = f"ITEMS{sm[1]}"
    src_dir = REPO / "game" / "items" / set_name
    files = sorted(src_dir.glob("*.toml"))
    if not files:
        raise Invalid(f"no .toml files under {src_dir.relative_to(REPO)}")
    rows, errors = {}, []
    for f in files:
        try:
            index, row = parse_item(f, id_prefix)
            if index in rows:
                raise Invalid(f"duplicate index {index}")
            rows[index] = row
        except Invalid as e:
            errors.append(f"{f.relative_to(REPO)}: {e}")
    if errors:
        raise Invalid("\n".join(errors))
    expected = list(range(len(rows)))
    if sorted(rows) != expected:
        raise Invalid(f"{src_dir.relative_to(REPO)}: indices must be contiguous from 0")
    rel_src = src_dir.relative_to(REPO).as_posix()
    lines = [
        f"// Generated by tools/compile_items.py from {rel_src}/*.toml — do not edit by hand.",
        "#[rustfmt::skip]",
        "pub static ITEMS: &[ItemDesign] = &[",
    ]
    lines += [f"    {rows[i]}," for i in expected]
    lines.append("];")
    generated = "\n".join(lines) + "\n"
    begin, end = f"// BEGIN GENERATED {region}\n", f"// END GENERATED {region}\n"
    text = out_path.read_text(encoding="utf-8")
    b, e = text.find(begin), text.find(end)
    if b < 0 or e < 0 or e < b:
        raise SystemExit(f"{out_path.relative_to(REPO)}: markers for {region} not found")
    new_text = text[: b + len(begin)] + generated + text[e:]
    if new_text != text and not check:
        out_path.write_text(new_text, encoding="utf-8")
    return len(rows), new_text != text


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--set", default="set1")
    ap.add_argument("--out", default="rust/tapstone-progression/src/items.rs")
    ap.add_argument("--check", action="store_true",
                    help="exit 3 if the committed file differs, write nothing")
    args = ap.parse_args()
    out_path = (REPO / args.out).resolve()
    try:
        n, changed = compile_items(args.set, out_path, check=args.check)
    except Invalid as e:
        print(e, file=sys.stderr)
        return 2
    rel = out_path.relative_to(REPO)
    if args.check:
        if changed:
            print(f"{rel} is stale: run tools/compile_items.py")
            return 3
        print(f"{args.set}: {n} items, {rel} is up to date")
        return 0
    print(f"{args.set}: {n} items -> {rel} ({'updated' if changed else 'unchanged'})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
