//! Card designs. The engine only ever sees a design index (`u16`); UIDs stay in the registry.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Faction {
    Ember,
    Tide,
    Neutral,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Keyword {
    Ranged,
    Shield1,
    Haste,
    Rush,
    Taunt,
}

impl Keyword {
    /// The closed list in wire order. A commander's keyword travels as this code in `ClaimSeat`'s
    /// `lane` byte and in the canonical image (0029); `Option::None` is 0xFF / -1.
    const ALL: [Keyword; 5] = [
        Keyword::Ranged,
        Keyword::Shield1,
        Keyword::Haste,
        Keyword::Rush,
        Keyword::Taunt,
    ];

    pub const fn code(self) -> u8 {
        self as u8
    }

    pub const fn from_code(code: u8) -> Option<Keyword> {
        if (code as usize) < Self::ALL.len() {
            Some(Self::ALL[code as usize])
        } else {
            None
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Effect {
    Damage { amount: u8, castle_ok: bool },
    Heal { amount: u8 },
    Destroy { max_toughness: u8 },
    Shift, // move target unit one lane (direction in the tap's aux byte)
    Draw { count: u8 },
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CardKind {
    Unit {
        attack: u8,
        toughness: u8,
        keyword: Option<Keyword>,
    },
    Spell(Effect),
    Castle,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct CardDesign {
    pub id: u16,
    pub name: &'static str,
    pub faction: Faction,
    pub cost: u8,
    pub kind: CardKind,
}

const fn unit(
    id: u16,
    name: &'static str,
    faction: Faction,
    cost: u8,
    attack: u8,
    toughness: u8,
    keyword: Option<Keyword>,
) -> CardDesign {
    CardDesign {
        id,
        name,
        faction,
        cost,
        kind: CardKind::Unit {
            attack,
            toughness,
            keyword,
        },
    }
}
const fn spell(
    id: u16,
    name: &'static str,
    faction: Faction,
    cost: u8,
    effect: Effect,
) -> CardDesign {
    CardDesign {
        id,
        name,
        faction,
        cost,
        kind: CardKind::Spell(effect),
    }
}

const fn castle(id: u16, name: &'static str, faction: Faction) -> CardDesign {
    CardDesign {
        id,
        name,
        faction,
        cost: 0,
        kind: CardKind::Castle,
    }
}

/// The set 1 test designs. The region below is generated from game/cards/set1/*.toml by
/// tools/compile_cards.py; edit the TOML, not this block.
// BEGIN GENERATED SET1
// Generated by tools/compile_cards.py from game/cards/set1/*.toml — do not edit by hand.
#[rustfmt::skip]
pub static SET1: &[CardDesign] = &[
    castle(0, "Ember Castle", Faction::Ember),
    castle(1, "Tide Castle", Faction::Tide),
    unit(2, "Cinder Whelp", Faction::Ember, 1, 2, 1, Some(Keyword::Haste)),
    unit(3, "Ashen Vanguard", Faction::Ember, 3, 3, 2, Some(Keyword::Rush)),
    unit(4, "Hearth Warden", Faction::Ember, 2, 1, 3, Some(Keyword::Taunt)),
    spell(5, "Flare", Faction::Ember, 1, Effect::Damage { amount: 2, castle_ok: true }),
    unit(6, "Reef Archer", Faction::Tide, 2, 1, 2, Some(Keyword::Ranged)),
    unit(7, "Tidecaller", Faction::Tide, 3, 2, 3, None),
    unit(8, "Pearl Shieldbearer", Faction::Tide, 2, 1, 2, Some(Keyword::Shield1)),
    spell(9, "Tidal Lash", Faction::Tide, 2, Effect::Damage { amount: 3, castle_ok: false }),
    spell(10, "Undertow", Faction::Tide, 2, Effect::Shift),
    spell(11, "Deep Breath", Faction::Neutral, 1, Effect::Draw { count: 2 }),
    spell(12, "Mend", Faction::Neutral, 1, Effect::Heal { amount: 2 }),
    spell(13, "Riptide", Faction::Tide, 3, Effect::Destroy { max_toughness: 2 }),
    unit(14, "Forge Runner", Faction::Ember, 2, 2, 2, Some(Keyword::Haste)),
    unit(15, "Bellows Raider", Faction::Ember, 2, 2, 1, Some(Keyword::Rush)),
    unit(16, "Slag Brute", Faction::Ember, 4, 4, 3, None),
    spell(17, "Magma Burst", Faction::Ember, 3, Effect::Damage { amount: 3, castle_ok: true }),
    unit(18, "Brine Skimmer", Faction::Tide, 1, 1, 1, Some(Keyword::Ranged)),
    unit(19, "Trench Leviathan", Faction::Tide, 4, 3, 4, Some(Keyword::Shield1)),
];
// END GENERATED SET1

pub fn design(id: u16) -> Option<&'static CardDesign> {
    SET1.get(id as usize)
}
